version: '3.8'

services:
  sut:
    image: justeatcypresstests
    ipc: host
    build: .
    environment:
      CYPRESS_RECORD_KEY: $CYPRESS_RECORD_KEY
    volumes:
      - ./cypress/videos:/usr/src/app/cypress/videos
      - ./cypress/screenshots:/usr/src/app/cypress/screenshots
      - ./cypress/reports:/usr/src/app/cypress/reports
      - ./cypress/results:/usr/src/app/cypress/results
