version: 2.1
workflows:
    "Cypress tests":
        jobs:
          - cypress-tests
jobs:
  cypress-tests:
    docker:
      - image: cypress/browsers:node12.18.3-chrome87-ff82
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package-lock.json" }}
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules  
          key: npm-deps-{{ checksum "package-lock.json" }}
      - run: npm ci
      - run: npm test
