name: Browserstack Cypress Tests

on: [push, pull_request]

jobs:
  test:
    name: Browserstack tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Browserstack Cypress CLI
        run: sudo npm install -g browserstack-cypress-cli
      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@master'
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: BUILD_INFO
          project-name: REPO_NAME
      - name: Run tests
        run: npm run browserstack-tests
